export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 15 Pro (256 GB) - Natural Titanium",
      imgSrc: 'https://m.media-amazon.com/images/I/81CgtwSII3L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'GAME-CHANGING A17 PRO CHIP,CUSTOMIZABLE ACTION BUTTON',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71D-xbvtz-L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Intel i5 11thgen (16 GB, 512 GB) irix xe graphics',
      price: '49999',
    },

    {
      id: 11,
      category: 'mobiles',
      title: "Samsung Galaxy S23 Ultra 5G (Cream, 12GB, 256GB Storage)",
      imgSrc: 'https://m.media-amazon.com/images/I/61j99uUfXNL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/i5WzMBP',
      description: 'FASTEST MOBILE PROCESSOR AVAILABLE, 200MP camera, Unlocked for All Carriers ',
      price: '69999',
    },
    
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 15 (128 GB)-Black",
      imgSrc: 'https://m.media-amazon.com/images/I/71657TiFeHL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/aDLxDfV',
      description: '48MP Main camera,Super Retina XDR display, A16 Bionic ',
      price: '79999',
    },
    {
      id: 13,
      category: 'laptops',
      title: "Samsung Galaxy Book3 360 Intel 13th Gen i7",
      imgSrc: 'https://m.media-amazon.com/images/I/71tPWK3MzHL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/hBn9TDo',
      description: 'Super Amoled 2-in-1 Touchscreen Laptop (16 GB/512GB SSD/Fingerprint Sensor/Graphite/1.16Kg)',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/71LRY1j6UHL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    {
      id: 12,
      category: 'mobiles',
      title: "OnePlus 11R 5G (Galactic Silver, 8GB RAM, 128GB Storage)",
      imgSrc: 'https://m.media-amazon.com/images/I/613SAOPmLeL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/fORT8rN',
      description: 'Processor: Snapdragon 8+ Gen 1 ,5000 mAh with 100W SuperVOOCOperating',
      price: '69999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB,)',
      price: '19999',
    },
    {
      id: 14,
      category: 'laptops',
      title: "ASUS Vivobook Go 15",
      imgSrc: 'https://m.media-amazon.com/images/I/61zx5wnGibL._SY450_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'AMD Ryzen 5 7520U, 15.6"FHD,Thin & Light Laptop (16GB/512GB SSD/Windows 11)',
      price: '39999',
    },
    
    {
      id: 3,
      category: 'mobiles',
      title: "IQOO 11 5G",
      imgSrc: 'https://m.media-amazon.com/images/I/71ZeuCAbcSL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/gVIDfMO',
      description: '8GB RAM, 256 GB Storage| Snapdragon 8 Gen 2 Mobile Platform| 2K E6 AMOLED Display| V2 Intelligent Display Chip',
      price: '69999',
    },
    {
      id: 17,
      category: 'tablets',
      title: "realme Pad X WiFi+5G Tablet",
      imgSrc: 'https://m.media-amazon.com/images/I/61OduK+OwBL._SX522_.jpg',
      amazonLink: 'https://amzn.eu/d/9UO0mVM',
      description: '6GB RAM 128GB ROM Expandable,(11 inch)| 6nm SD Processor | Dolby Atmos Quad Speakers | 8340 mAh Battery | Blue Colour',
      price: '29999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/61wLTc0YixL._SY450_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29999',
    },
    {
      id: 15,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/91veRYPjpeL._SX450_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '19999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "ASUS ROG Strix G15, AMD Ryzen 7 6800H",
      imgSrc: 'https://m.media-amazon.com/images/I/71m7XVxRD-L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: '15.6"(39.62 cm) FHD 144Hz, 4GB RTX 3050,(16GB/1TB SSD/Win11/Office 21/2.1 Kg)',
      price: '89999',
    },
    {
      id: 18,
      category: 'tablets',
      title: "Samsung Galaxy Tab S9 FE+",
      imgSrc: 'https://m.media-amazon.com/images/I/61HX7IoHIIL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/d28QZ53',
      description: 'Exynos 1380 chip, (12.4 inch) Display, 8 GB + 128 (Expandable), S Pen in-Box, WiFi+5G, IP68 Tablet,90 Hz Refresh Rate, Silver',
      price: '49999',
    },
    {
      id: 10,
      category: 'mobiles',
      title: "Samsung Galaxy S23 5G (Green, 8GB, 128GB Storage)",  
      imgSrc: 'https://m.media-amazon.com/images/I/61RZDb2mQxL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/2E3Qlz7',
      description: 'Snapdragon 8 Gen 2,Unlocked for All Carriers ',
      price: '69999',
    },
    {
      id: 19,
      category: 'tablets',
      title: "Google Pixel Tablet",
      imgSrc: 'https://m.media-amazon.com/images/I/61PVX-Qk0KL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/dcRsuQI',
      description: '8+128 GB, Tensor G2, Android Tablet with 11-Inch Screen, Smart Home Controls, and Long-Lasting Battery - Porcelain',
      price: '49999',
    },
    {
      id: 16,
      category: 'laptops',
      title: "HONOR MagicBook X14",
      imgSrc: 'https://m.media-amazon.com/images/I/71lMEeDJhuL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/6kp37kO',
      description: '12th Gen Intel Core i5-12450H (8GB/512GB NVMe SSD, 14-inch (35.56 cm) FHD IPS Anti-Glare Thin and Light',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "OnePlus Pad",
      imgSrc: 'https://m.media-amazon.com/images/I/61QnhDo0FEL._SX679_.jpg',
      amazonLink: 'https://amzn.eu/d/eOsjLJI',
      description: 'LCD Display, 12GB RAM,256GB Storage, MediaTek Dimensity 9000, 144HZ Refresh Rate, Dolby Vision Atmos',
      price: '39999',
    },
   
   



  ]